In [46]:
import re
import math
import numpy as np
import pandas as pd
from datetime import datetime
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import GradientBoostingClassifier
from lightgbm import LGBMClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score ,precision_score , recall_score , confusion_matrix , f1_score
from sklearn.model_selection import GridSearchCV
from ast import literal_eval
from gensim.models.keyedvectors import KeyedVectors
from sklearn.decomposition import PCA
pca = PCA(n_components=40)
from sklearn import datasets, metrics, model_selection
import matplotlib.pyplot as plt
from sklearn.metrics import roc_curve, auc
from sklearn.metrics import roc_auc_score

In [47]:
#data_train = pd.read_csv('./data/twitter_data_before_analysis.csv', error_bad_lines=False)
data_train = pd.read_csv('./data/twitter_data_before_analysis1.csv', error_bad_lines=False)
data_train = data_train.append(pd.read_csv('./data/ko_news_data_before_analysis.csv', error_bad_lines=False))
data_train = data_train.append(pd.read_csv('./data/en_news_data_before_analysis.csv', error_bad_lines=False))

In [48]:
data_train['period'] = pd.to_numeric(data_train['period'], errors='coerce')
data_train['category'] = pd.to_numeric(data_train['category'], errors='coerce')
data_train['label'] = pd.to_numeric(data_train['label'], errors='coerce')
data_train['Silhouette'] = pd.to_numeric(data_train['Silhouette'], errors='coerce')

In [49]:
compl_result = data_train[data_train['result']==3].index

In [50]:
data_train = data_train.drop(compl_result)

In [51]:
x_data_df = data_train[data_train.columns.difference(['label'])]

In [52]:
#x_data_df = data_train[['period','raw_data','closer#','category','label','Silhouette']]
y_data_df = data_train['label']

In [53]:
x_data_df = x_data_df.drop('Unnamed: 0', axis=1)
x_data_df = x_data_df.drop('result', axis=1)
x_data_df = x_data_df.drop('Silhouette', axis=1)

In [ ]:
X_train = x_data_df
y_train = y_data_df

In [ ]:
data_test = pd.read_csv('./data/(test)_twitter_data_before_analysis.csv', error_bad_lines=False)
data_test = data_test.append(pd.read_csv('./data/(test)_ko_news_data_before_analysis.csv', error_bad_lines=False))
data_test = data_test.append(pd.read_csv('./data/(test)_en_news_data_before_analysis.csv', error_bad_lines=False))

In [ ]:
data_test['period'] = pd.to_numeric(data_test['period'], errors='coerce')
data_test['category'] = pd.to_numeric(data_test['category'], errors='coerce')
data_test['label'] = pd.to_numeric(data_test['label'], errors='coerce')
data_test['Silhouette'] = pd.to_numeric(data_test['Silhouette'], errors='coerce')

In [ ]:
X_test = data_test[data_test.columns.difference(['label','result','Silhouette','Unnamed: 0'])]
y_test = data_test['label']

In [ ]:
#y_train

In [54]:
rf_clf = RandomForestClassifier(random_state = 11 ,n_jobs=-1) # random forest

In [55]:
data_test = pd.read_csv('./data/(test)_twitter_data_before_analysis.csv', error_bad_lines=False)
data_test = data_test.append(pd.read_csv('./data/(test)_ko_news_data_before_analysis.csv', error_bad_lines=False))
data_test = data_test.append(pd.read_csv('./data/(test)_en_news_data_before_analysis.csv', error_bad_lines=False))

In [56]:
data_test['period'] = pd.to_numeric(data_test['period'], errors='coerce')
data_test['category'] = pd.to_numeric(data_test['category'], errors='coerce')
data_test['label'] = pd.to_numeric(data_test['label'], errors='coerce')
data_test['Silhouette'] = pd.to_numeric(data_test['Silhouette'], errors='coerce')

In [57]:
X_test = data_test[data_test.columns.difference(['label','result','Silhouette','Unnamed: 0'])]
y_test = data_test['label']

In [58]:
#y_train

In [59]:
rf_clf = RandomForestClassifier(random_state = 11 ,n_jobs=-1) # random forest

In [60]:
rf_clf.fit(X_train, y_train)

y_score = rf_clf.predict_proba(X_test)



In [61]:
rf_pred = rf_clf.predict(X_test)  # random forest predict

In [62]:
print('Random Forest Accuracy :  ',accuracy_score(y_test,rf_pred))
print('Random Forest Precision :  ',precision_score(y_test,rf_pred,pos_label='positive',average='weighted'))
print('Random Forest Recall :  ',recall_score(y_test,rf_pred,pos_label='positive',average='weighted'))
print('Random Forest f1 :  ',f1_score(y_test,rf_pred,pos_label='positive',average='weighted'))

Random Forest Accuracy :   0.5413004522570185
Random Forest Precision :   0.563782960420723
Random Forest Recall :   0.5413004522570185
Random Forest f1 :   0.5270000833773744


/Users/hongminpyo/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1270: UserWarning: Note that pos_label (set to 'positive') is ignored when average != 'binary' (got 'weighted'). You may use labels=[pos_label] to specify a single positive class.
  % (pos_label, average), UserWarning)
/Users/hongminpyo/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1221: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/hongminpyo/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1221: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [63]:
y_score

array([[0.04, 0.07, 0.  , ..., 0.03, 0.09, 0.12],
       [0.92, 0.06, 0.  , ..., 0.  , 0.  , 0.  ],
       [0.75, 0.12, 0.  , ..., 0.  , 0.04, 0.01],
       ...,
       [0.03, 0.01, 0.  , ..., 0.  , 0.  , 0.17],
       [0.03, 0.09, 0.  , ..., 0.  , 0.02, 0.21],
       [0.  , 0.05, 0.  , ..., 0.  , 0.01, 0.25]])

In [64]:
dt_clf = DecisionTreeClassifier(random_state = 11)
dt_clf.fit(X_train,y_train)
dt_pred = dt_clf.predict(X_test)

In [65]:
print('Decision Tree Accuracy :  ',accuracy_score(y_test,dt_pred))
print('Decision Tree Precision :  ',precision_score(y_test,dt_pred,pos_label='positive',average='weighted'))
print('Decision Tree Recall :  ',recall_score(y_test,dt_pred,pos_label='positive',average='weighted'))
print('Decision Tree f1 :  ',f1_score(y_test,dt_pred,pos_label='positive',average='weighted'))

Decision Tree Accuracy :   0.7053502858605684
Decision Tree Precision :   0.6785372046636267
Decision Tree Recall :   0.7053502858605684
Decision Tree f1 :   0.6881237790012673


/Users/hongminpyo/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1270: UserWarning: Note that pos_label (set to 'positive') is ignored when average != 'binary' (got 'weighted'). You may use labels=[pos_label] to specify a single positive class.
  % (pos_label, average), UserWarning)
/Users/hongminpyo/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1221: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [66]:
#gb_clf = GradientBoostingClassifier(random_state = 11) # random forest
lgbm_clf =  LGBMClassifier(random_state = 11)

In [67]:
#gb_clf.fit(X_train,y_train)
#gb_pred = gb_clf.predict(X_test)

lgbm_clf.fit(X_train,y_train)
lgbm_pred = lgbm_clf.predict(X_test)

In [68]:
#print('Gredient Boosting Accuracy :  ',accuracy_score(y_test,gb_pred))
#print('Gredient Boosting Precision :  ',precision_score(y_test,gb_pred,pos_label='positive',average='weighted'))
#print('Gredient Boosting Recall :  ',recall_score(y_test,gb_pred,pos_label='positive',average='weighted'))
#print('Gredient Boosting f1 :  ',f1_score(y_test,gb_pred,pos_label='positive',average='weighted'))
print('Light GBM Accuracy :  ',accuracy_score(y_test,lgbm_pred))
print('Light GBM Precision :  ',precision_score(y_test,lgbm_pred,pos_label='positive',average='weighted'))
print('Light GBM Recall :  ',recall_score(y_test,lgbm_pred,pos_label='positive',average='weighted'))
print('Light GBM f1 :  ',f1_score(y_test,lgbm_pred,pos_label='positive',average='weighted'))

Light GBM Accuracy :   0.6740336206160935
Light GBM Precision :   0.661642548141314
Light GBM Recall :   0.6740336206160935
Light GBM f1 :   0.6655912144329764


In [69]:
lr_clf = LogisticRegression(random_state = 11)

In [70]:
lr_clf.fit(X_train,y_train)
lr_pred = lr_clf.predict(X_test)

In [71]:
print('Logistic Regression Accuracy :  ',accuracy_score(y_test,lr_pred))
print('Logistic Regression  Precision :  ',precision_score(y_test,lr_pred,pos_label='positive',average='weighted'))
print('Logistic Regression  Recall :  ',recall_score(y_test,lr_pred,pos_label='positive',average='weighted'))
print('Logistic Regression  f1 :  ',f1_score(y_test,lr_pred,pos_label='positive',average='weighted'))

Logistic Regression Accuracy :   0.5276047444321188
Logistic Regression  Precision :   0.27836676634728136
Logistic Regression  Recall :   0.5276047444321188
Logistic Regression  f1 :   0.3644486800160641


/Users/hongminpyo/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1270: UserWarning: Note that pos_label (set to 'positive') is ignored when average != 'binary' (got 'weighted'). You may use labels=[pos_label] to specify a single positive class.
  % (pos_label, average), UserWarning)
/Users/hongminpyo/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1221: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [72]:
from numpy import loadtxt
from keras.models import Sequential
from keras.layers import Dense

In [73]:
model = Sequential()
model.add(Dense(120, input_dim=103, activation='relu'))
model.add(Dense(80, activation='relu'))
model.add(Dense(60, activation='relu'))
model.add(Dense(40, activation='relu'))
model.add(Dense(20, activation='relu'))
model.add(Dense(13, activation='softmax'))

In [74]:
# compile the keras model
#model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

In [75]:
from keras.utils import to_categorical

y_train = y_train.apply(lambda x : x-1)

In [76]:
y_cate_train = to_categorical(y_train , num_classes=13)
#y_cate_train = y_train

In [77]:
model.fit(X_train,y_cate_train, epochs=30, batch_size=500)

Epoch 1/30
152054/152054 [==============================] - 1s 7us/step - loss: 226.1203 - accuracy: 0.2242
Epoch 2/30
152054/152054 [==============================] - 1s 6us/step - loss: 17.3355 - accuracy: 0.1609
Epoch 3/30
152054/152054 [==============================] - 1s 6us/step - loss: 2.5533 - accuracy: 0.1586
Epoch 4/30
152054/152054 [==============================] - 1s 6us/step - loss: 2.3290 - accuracy: 0.2887
Epoch 5/30
152054/152054 [==============================] - 1s 6us/step - loss: 2.1974 - accuracy: 0.2887
Epoch 6/30
152054/152054 [==============================] - 1s 6us/step - loss: 2.0986 - accuracy: 0.2887
Epoch 7/30
152054/152054 [==============================] - 1s 6us/step - loss: 2.0285 - accuracy: 0.2913
Epoch 8/30
152054/152054 [==============================] - 1s 6us/step - loss: 1.9815 - accuracy: 0.3271
Epoch 9/30
152054/152054 [==============================] - 1s 6us/step - loss: 1.9517 - accuracy: 0.3271
Epoch 10/30
152054/152054 [================

In [78]:
y_test = y_test.apply(lambda x : x-1)

In [79]:
y_cate_test = to_categorical(y_test , num_classes=13)

In [80]:
score = model.evaluate(X_test, y_cate_test, batch_size=500)

23438/23438 [==============================] - 0s 4us/step


In [81]:
score

[1.6771841516001598, 0.5276047587394714]

In [82]:
yhat_probs = model.predict(X_test ,batch_size=500 )

yhat_classes = model.predict_classes(X_test ,batch_size=500 )

# reduce to 1d array
#yhat_probs = yhat_probs[:, 0]
#yhat_classes = yhat_classes[:, 0]

In [83]:
yhat_classes

array([5, 5, 5, ..., 5, 5, 5])

In [84]:
y_cate_test

array([[0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

In [85]:
# accuracy: (tp + tn) / (p + n)
accuracy = accuracy_score(y_test, yhat_classes )
print('Accuracy: %f' % accuracy)
# precision tp / (tp + fp)
precision = precision_score(y_test, yhat_classes , average='micro')
print('Precision: %f' % precision)
# recall: tp / (tp + fn)
recall = recall_score(y_test, yhat_classes , average='micro')
print('Recall: %f' % recall)
# f1: 2 tp / (2 tp + fp + fn)
f1 = f1_score(y_test, yhat_classes,average='micro')
print('F1 score: %f' % f1)

Accuracy: 0.527605
Precision: 0.527605
Recall: 0.527605
F1 score: 0.527605
